---
- name: Update and upgrade apt packages
  become: yes
  apt: update_cache=yes cache_valid_time=600 upgrade=dist

- name: Install System Packages
  become: yes
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - htop
    - ufw

- name: Set up authorized_keys
  authorized_key: user={{ system_user }} key="{{ item }}"
  with_file:
    - authorized_keys/nick.key

- name: Disallow root SSH access
  become: yes
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: restart ssh

- name: Disallow password logins
  become: yes
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart ssh

- name: Add system user to adm group (for logs)
  become: yes
  user: name={{ system_user }} groups=adm append=yes

- name: cd into {{ login_root }} on login
  lineinfile: dest="{{ ansible_env.HOME}}/.bashrc" line="cd {{ login_root }}" state=present
