version: '3'
services:
  nginx-rtmp:
    build:
      context: ./docker/nginx-rtmp
    image: nginx-rtmp:flaq
    container_name: nginx-rtmp-flaq
    networks:
      - flaq-network
    volumes:
      - flaq-volume:/var/www

networks:
  flaq-network:

volumes:
  flaq-volume:
    driver: local
