---
- name: Install nginx-rtmp dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - ffmpeg
    - libpcre3
    - libpcre3-dev
    - libssl-dev

- name: Create build directory
  file: path={{ build_directory }} state=directory

- name: Download & unpack latest nginx-rtmp
  unarchive:
    src: https://github.com/arut/nginx-rtmp-module/archive/v{{ rtmp_version }}.tar.gz
    dest: "{{ build_directory }}"
    remote_src: True
    creates: "{{ build_directory }}/nginx-rtmp-module-{{ rtmp_version }}"

- name: Download & unpack nginx source
  unarchive:
    src: http://nginx.org/download/nginx-{{ nginx_version }}.tar.gz
    dest: "{{ build_directory }}"
    remote_src: True
    creates: "{{ build_directory }}/nginx-{{ nginx_version }}"

- name: Build nginx with nginx-rtmp
  command: "{{ item }}"
  args:
    chdir: "{{ build_directory }}/nginx-{{ nginx_version }}"
    creates: /usr/local/nginx/sbin/nginx
  with_items:
    - "./configure --with-http_ssl_module --add-module={{ build_directory }}/nginx-rtmp-module-{{ rtmp_version }}"
    - sudo make
    - sudo make install

- name: Configure nginx and nginx-rtmp
  template: src=nginx.conf dest=/usr/local/nginx/conf/nginx.conf

- name: Configure nginx systemd service
  template:
    src: nginx.service
    dest: /lib/systemd/system/nginx.service
    owner: root
    group: root
    mode: 0664
  notify: reload nginx
