---
- name: Install nginx-rtmp dependencies
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - ffmpeg

- name: Ensure live, record and thumbnail direcories are created
  become: yes
  file:
    path: "{{ item }}"
    owner: www-data
    group: www-data
    state: directory
  with_items:
    - "{{ rtmp_live_path }}"
    - "{{ rtmp_record_path }}"
    - "{{ rtmp_thumbnail_path }}"

- name: Add rtmp publishing configuration
  become: yes
  template:
    src: rtmp.conf
    dest: /etc/nginx/rtmp.conf

- name: Enable rtmp publishing
  become: yes
  lineinfile:
    path: /etc/nginx/nginx.conf
    state: present
    regexp: include /etc/nginx/rtmp.conf;
    line: include /etc/nginx/rtmp.conf;
  notify: reload nginx

- name: Add rtmp playback configuration
  become: yes
  template:
    src: ingest.flaq.live
    dest: /etc/nginx/sites-available/ingest.flaq.live

- name: Enable rtmp playback
  become: yes
  file:
    src: /etc/nginx/sites-available/ingest.flaq.live
    dest: /etc/nginx/sites-enabled/ingest.flaq.live
    state: link
  notify: reload nginx
