---
- hosts: all
  remote_user: "{{ system_user }}"
  roles:
    - core

# - hosts: web
#   remote_user: "{{ system_user }}"
#   roles:
#     - { role: flaq-web }

- hosts: api
  remote_user: "{{ system_user }}"
  roles:
    - flaq-api

- hosts: ingest
  remote_user: "{{ system_user }}"
  roles:
    - nginx-rtmp
