---
- name: Make the {{ system_user }} user the owner of $GOPATH
  become: yes
  file:
    path: "{{ ansible_env.HOME}}/go"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    state: directory
    recurse: yes

- name: Checkout nicklaw5/flaq
  git:
    repo: ssh://git@github.com/nicklaw5/flaq.git
    dest: "{{ flaq_directory }}"
    accept_hostkey: yes
  when: is_prod is defined and is_prod

- name: Build the Flaq API application
  command: "/usr/local/go/bin/go build -o {{ flaq_bin_directory }}/flaq"
  args:
    chdir: "{{ flaq_api_directory }}"
    creates: "{{ flaq_bin_directory }}/flaq"

- name: Create Flaq API service
  become: yes
  template:
    src: "{{ flaq_service_name }}"
    dest: /etc/systemd/system/{{ flaq_service_name }}
    owner: root
    group: root
    mode: 0664

- name: Ensure Flaq API is enabled
  become: yes
  shell: |
    systemctl enable {{ flaq_service_name }}
    exit 0

- name: Ensure Flaq API is started
  become: yes
  shell: |
    systemctl start {{ flaq_service_name }}
    exit 0
