---
- name: Make the {{ system_user }} user the owner of $GOPATH
  become: yes
  file:
    path: "{{ ansible_env.HOME}}/go"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    state: directory
    recurse: yes

- name: Checkout nicklaw5/flaq
  git:
    repo: ssh://git@github.com/nicklaw5/flaq.git
    dest: "{{ flaq_api_directory }}"
    accept_hostkey: yes
  when: is_prod is defined and is_prod

- name: Import Flaq API dependencies
  command: /usr/local/go/bin/go get ./...
  args:
    chdir: "{{ flaq_api_directory }}"

- name: Build the Flaq API application
  command: /usr/local/go/bin/go build -o flaq
  args:
    chdir: "{{ flaq_api_directory }}"
    creates: "{{ flaq_api_directory }}/flaq"

- name: Create Flaq API service
  become: yes
  template:
    src: "{{ flaq_api_service }}"
    dest: /etc/systemd/system/{{ flaq_api_service }}
    owner: root
    group: root
    mode: 0664

- name: Ensure Flaq API is enabled
  become: yes
  shell: |
    systemctl enable {{ flaq_api_service }}
    exit 0

- name: Ensure Flaq API is started
  become: yes
  shell: |
    systemctl start {{ flaq_api_service }}
    exit 0
